### PR TITLE
Collision management

### PR DESCRIPTION
**Pull request by gdozot2**

### CODE REVIEW

**Comment by slecorne** [comment]
could you check if Intersection Observer can be used instead? https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API
It would probably clean the code and avoid checking at each mouse move event multiple images

**Comment by gdozot2** [comment]
Sure, I check

**Review by slecorne — COMMENTED** [review]
Ok for me to merge, you may want to try the intersection observer in a new PR

**Comment by gdozot2** [comment]
Yeah, I think it's better and easy to test in another branch

**Pull request merged**
